using System.Collections.Generic;

namespace KrantenJongen.DTO;

public record Source(string Name, string Url, string Selector)
{
    public static readonly IReadOnlyCollection<Source> Sources = new List<Source>
    {
        new("Government of the Netherlands", "https://feeds.government.nl/news.rss", "//*[@id=\"content-wrapper\"]"),

        new("Gemeente Amsterdam", "https://www.amsterdam.nl/nieuws/nieuwsoverzicht/?rss=true", "//*[@id=\"Content\"]"),

        new("NL Times", "https://nltimes.nl/rssfeed2", "//article[1]"),
        new("nieuws.nl", "https://nieuws.nl/sitemap/news.xml", "/html/body"),
        new("DutchNews.nl", "https://www.dutchnews.nl/feed/", "//*[@id=\"main\"]/article"),
        new("RTL Nieuws", "https://www.rtlnieuws.nl/rss.xml", "//*[@id=\"app\"]/div/main"),
        new("IamExpat.nl", "https://www.iamexpat.nl/rss/news-netherlands", "//*[@id=\"block-system-main\"]/div/div/article/div[2]"),
        new("Новости Нидерландов", "https://www.novostiniderlandov.com/feed/", "//*[@id=\"primary\"]/div/div/div/main/article"),
        new("NU.nl", "https://www.nu.nl/rss", "//*[@id=\"main\"]/article"),
        new("Nederlands Dagblad", "https://www.nd.nl/rss/nieuws", "//article[1]"),
        new("Het Financieele Dagblad", "https://fd.nl/?rss", string.Empty),
        new("GeenStijl", "https://www.geenstijl.nl/feeds/recent.atom", "//main[1]"),

        new("BRIGHT.nl", "https://www.bright.nl/rss/index.xml", "//article[1]"),

        new("Metro", "https://www.metronieuws.nl/in-het-nieuws/feed/", "//article[1]"),
        new("Metro", "https://www.metronieuws.nl/entertainment/feed/", "//article[1]"),
        new("Metro", "https://www.metronieuws.nl/geld-carriere/feed/", "//article[1]"),
        new("Metro", "https://www.metronieuws.nl/lifestyle/feed/", "//article[1]"),
        new("Metro", "https://www.metronieuws.nl/winacties/feed/", "//article[1]"),

        new("Het Parool", "https://www.parool.nl/voorpagina/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/onrust-in-amsterdam/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/topverhalen/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/amsterdam/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/nederland/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/idfa/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/kunst-media/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/uit-in-amsterdam/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/columns-opinie/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/sport/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/ps/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/deja-vu/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/podcasts/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/boeken/rss.xml", string.Empty),
        new("Het Parool", "https://www.parool.nl/popular/rss.xml", string.Empty),

        new("AD.nl", "https://www.ad.nl/home/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/praat-mee/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/auto/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/geld/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/koken-eten/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/wonen/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/gezond/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/achter-de-schermen/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/nieuws/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/binnenland/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/buitenland/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/politiek/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/economie/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/bizar/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/wetenschap/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/reizen/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/opinie/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/quiz/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/sport/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/nederlands-voetbal/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/buitenlands-voetbal/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/formule-1/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/wielrennen/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/darts/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/vechtsport/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/tennis/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/andere-sporten/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/offside/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/transfer-talk/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/schaatsen/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/show/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/sterren/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/film/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/songfestival/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/muziek/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/showbytes/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/royalty/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/cultuur/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/tv-radio/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/musical-theater/rss.xml", string.Empty),
        new("AD.nl", "https://www.ad.nl/series/rss.xml", string.Empty),

        new("De Telegraaf", "https://www.telegraaf.nl/rss", string.Empty),
        new("De Telegraaf", "https://www.telegraaf.nl/nieuws/rss", string.Empty),
        new("De Telegraaf", "https://www.telegraaf.nl/sport/rss", string.Empty),
        new("De Telegraaf", "https://www.telegraaf.nl/entertainment/rss", string.Empty),
        new("De Telegraaf", "https://www.telegraaf.nl/financieel/rss", string.Empty),
        new("De Telegraaf", "https://www.telegraaf.nl/vrouw/rss", string.Empty),
        new("De Telegraaf", "https://www.telegraaf.nl/video/rss", string.Empty),
        new("De Telegraaf", "https://www.telegraaf.nl/watuzegt/rss", string.Empty),
        new("De Telegraaf", "https://www.telegraaf.nl/lifestyle/rss", string.Empty),

        new("De Volkskrant", "https://www.volkskrant.nl/voorpagina/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/columns-van-de-dag/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/nieuws-achtergrond/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/volkskrantdossiers/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/columns-opinie/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/cartoons/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/cultuur-media/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/tentoonstellingen/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/boeken/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/films/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/games/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/muziek/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/nieuwe-series/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/theater/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/ditjes/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/podcasts/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/digitale-specials/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/foto-xl/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/puzzels-en-quizzen/rss.xml", "//*[@id=\"article-content\"]"),
        new("De Volkskrant", "https://www.volkskrant.nl/popular/rss.xml", "//*[@id=\"article-content\"]"),

        new("NOS.nl", "https://feeds.nos.nl/nosnieuwsalgemeen", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosnieuwsbinnenland", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosnieuwsbuitenland", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosnieuwspolitiek", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosnieuwseconomie", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosnieuwsopmerkelijk", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosnieuwskoningshuis", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosnieuwscultuurenmedia", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosnieuwstech", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossportalgemeen", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosvoetbal", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossportwielrennen", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossportschaatsen", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossporttennis", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossportformule1", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nieuwsuuralgemeen", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nosop3", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/jeugdjournaal", "//*[@id=\"main\"]/main"),
        new("NOS.nl", "https://feeds.nos.nl/nosnieuwsvideo", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossportschaatsenvideo", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossportwielrennenvideo", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossportvoetbalvideo", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossporttennisvideo", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://feeds.nos.nl/nossportformule1video", "//*[@id=\"content\"]"),
        new("NOS.nl", "https://podcast.npo.nl/feed/met-het-oog-op-morgen.xml", string.Empty),
        new("NOS.nl", "https://podcast.npo.nl/feed/de-stemming-van-vullings-en-van-der-wulp.xml", string.Empty),
        new("NOS.nl", "https://podcast.npo.nl/feed/nos-langs-de-lijn-sport-forum.xml", string.Empty),
        new("NOS.nl", "https://podcast.npo.nl/feed/nos-voetbalpodcast.xml", string.Empty),
        new("NOS.nl", "https://podcast.npo.nl/feed/nosop3techpodcast.xml", string.Empty),

        new("Trouw", "https://www.trouw.nl/opening/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/voorpagina/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/politiek/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/boeken/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/columnisten/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/verdieping/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/doen/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/dossiers/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/truckers-naar-de-top/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/duurzaamheid-economie/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/luister-truckers-naar-de-top/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/religie-filosofie/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/opinie/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/wetenschap/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/cultuur-media/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/recensiesfilm/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/sport/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/podcasts/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/speciaal-voor-abonnees/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/achterpagina/rss.xml", string.Empty),
        new("Trouw", "https://www.trouw.nl/popular/rss.xml", string.Empty),

        new("NRC", "https://www.nrc.nl/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/binnenland/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/buitenland/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/economie/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/den-haag/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/cultuur/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/wetenschap/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/sport/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/opinie/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/tech-en-media/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/boeken/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/leven/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/slim-leven/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/inbeeld/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/carriere/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/recht/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/podcast/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/archief/rss/", "//*[@id=\"main-content\"]/article"),
        new("NRC", "https://www.nrc.nl/index/magazine/rss/", "//*[@id=\"main-content\"]/article"),

//        new("Reformatorisch Dagblad", "https://www.rd.nl/rss-feed?name=laatste-nieuws", ".article-body"),
    };
}
